export enum FormularTypes {
  ART11_SUCEAVA = 'SUCEAVA – FORMULAR PROGRAMARE ART 11',
  ART11_IASI = 'IAȘI – FORMULAR PROGRAMARE ART 11',
  ART11_GALATI = 'GALAȚI – FORMULAR PROGRAMARE ART. 11',
  ART8_81__10_27 = 'BUCURESTI – FORMULAR PROGRAMARE ART. 8, 8.1, 10, 27',
  ART11_BUCURESTI = 'BUCURESTI – FORMULAR PROGRAMARE ART. 11',
}
